title:  YEIEJE
url:  "https://iwdstry.github.io/yeieje_pool"
baseurl:  ""
remote_theme: nicoelayda/celeste
markdown: kramdown
highlighter:  rouge

exclude:  ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:  pretty
paginate: 5
paginate_path:  /yeieje_pool/blog/

blog:
  truncated_preview:  false

sass:
  sass_dir: _sass
  style:

author:
  name: yeieje2
  url:  "https://iwdstry.github.io/yeieje_pool/"
  

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
