title:  Celeste
url:  "https://iwdstry.github.io/yeieje_pool"
baseurl:  ""

markdown: kramdown
highlighter:  rouge

exclude:  ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:  pretty
paginate: 5
paginate_path:  /blog/

blog:
  truncated_preview:  false

sass:
  sass_dir: _sass
  style:

author:
  name: Nico Elayda
  url:  nicoelayda.github.io
  email:  nico@elayda.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
